import json
import os

EN_NGE = {
    "nav_sys_online": "MAGI SYSTEM v2.0 // ONLINE",
    "nav_sys_class": "// NERV AGRICULTURAL DIVISION // CLASSIFIED",
    "hero_eyebrow": "// MAGI AGRICULTURAL INTELLIGENCE SYSTEM",
    "hero_title": "AMRITKRISHI",
    "enter_sys": "ENTER SYSTEM ►",
    "learn_more": "LEARN MORE ↓",
    "scroll": "↓ SCROLL TO EXPLORE ↓",
    "hero_sub1": "AI-powered crop intelligence for Indian farmers",
    "hero_sub2": "Real-time disease detection from leaf images",
    "hero_sub3": "Live market prices from 500+ mandi locations",
    "hero_sub4": "Available in Tamil | Hindi | English",
    "mission_typed": "> 140 MILLION INDIAN FARMERS. MOST WITHOUT ACCESS TO MODERN AGRICULTURAL INTELLIGENCE. AMRITKRISHI CHANGES THAT.",
    "mission_dir": "// MISSION DIRECTIVE",
    "mission_title": "THE PROBLEM",
    "prob1_label": "Crop yield lost to disease annually",
    "prob2_label": "Govt schemes unclaimed every year",
    "prob3_label": "Farmers exploited by price middlemen",
    "feat_sys": "// SYSTEM CAPABILITIES",
    "feat_title": "FEATURES",
    "feat1_title": "CROP INTELLIGENCE",
    "feat1_sub": "AI-powered recommendation",
    "feat1_desc": "Select any Indian state and district. Our Random Forest model analyzes real-time soil + weather data and recommends the highest-yield crop with confidence score.",
    "feat1_s1": "22 crop types", "feat1_s2": "93% accuracy", "feat1_s3": "All 28 states",
    "feat2_title": "BIOLOGICAL THREAT SCAN",
    "feat2_sub": "CNN disease detection",
    "feat2_desc": "Upload a leaf photo. Our MobileNetV2 neural network scans for 38 disease classes across 12 plant species and delivers diagnosis with treatment protocol.",
    "feat2_s1": "38 disease classes", "feat2_s2": "85%+ accuracy", "feat2_s3": "Real-time scan",
    "feat3_title": "ATMOSPHERIC INTELLIGENCE",
    "feat3_sub": "Live weather + farming alerts",
    "feat3_desc": "Real-time weather for every Indian city via OpenWeatherMap. Farming-specific alerts for drought, frost, fungal risk, and optimal sowing windows.",
    "feat3_s1": "Live data", "feat3_s2": "7-day forecast", "feat3_s3": "Farming alerts",
    "feat4_title": "MARKET INTEL",
    "feat4_sub": "Live mandi prices",
    "feat4_desc": "Real-time crop prices from Agmarknet across all Indian states. Price trend analytics, best-time-to-sell recommendations, and AI price prediction.",
    "feat4_s1": "500+ mandis", "feat4_s2": "Live prices", "feat4_s3": "Price prediction",
    "feat5_title": "MAGI QUERY INTERFACE",
    "feat5_sub": "Multilingual AI chatbot",
    "feat5_desc": "Powered by Google Gemini. Ask anything about farming in Tamil, Hindi, or English. Context-aware responses tailored to Indian agriculture.",
    "feat5_s1": "3 languages", "feat5_s2": "Gemini AI", "feat5_s3": "24/7 available",
    "feat6_title": "FEDERAL DIRECTIVES",
    "feat6_sub": "Government scheme finder",
    "feat6_desc": "15+ government schemes including PM-KISAN, PMFBY, and state-specific programs. Eligibility checker, deadline countdown, and direct application links.",
    "feat6_s1": "15+ schemes", "feat6_s2": "Eligibility check", "feat6_s3": "Direct apply",
    "stat_sys": "// SYSTEM METRICS",
    "stat_title": "BY THE NUMBERS",
    "stat1_l": "Indian Farmers", "stat1_d": "potential users across India",
    "stat2_l": "Crop Accuracy",  "stat2_d": "on test dataset",
    "stat3_l": "Disease Detect", "stat3_d": "MobileNetV2 accuracy",
    "stat4_l": "Disease Classes","stat4_d": "plant diseases detected",
    "stat5_l": "Crop Types",     "stat5_d": "recommendation supported",
    "stat6_l": "Languages",      "stat6_d": "Tamil, Hindi, English",
    "stat7_l": "Mandi Locations","stat7_d": "live price coverage",
    "stat8_l": "Govt Schemes",   "stat8_d": "discoverable schemes",
    "tech_sys": "// SYSTEM ARCHITECTURE",
    "tech_title": "TECH STACK",
    "demo_sys": "// SYSTEM DEMONSTRATION",
    "demo_title": "HOW IT WORKS",
    "demo_step": "// STEP {step} OF {total}",
    "d1_t": "Select State", "d1_d": "Click Tamil Nadu on the interactive India map",
    "d2_t": "Pick District", "d2_d": "Choose Chennai from the district grid",
    "d3_t": "AI Analyzes", "d3_d": "MAGI fetches live weather + soil data and runs ML model",
    "d4_t": "Get Result", "d4_d": "Rice recommended with 92% confidence + full farming guide",
    "d5_t": "Detect Disease", "d5_d": "Upload leaf photo → CNN scans 38 diseases in 2 seconds",
    "d6_t": "Ask AI in Tamil", "d6_d": "Type question in Tamil → Gemini responds in Tamil instantly",
    "enter_sys_rdy": "// SYSTEM READY",
    "enter_title": "ENTER AMRITKRISHI",
    "enter_typed": "> MAGI SYSTEM FULLY OPERATIONAL\\n> ALL MODULES ONLINE\\n> AWAITING OPERATOR INPUT...",
    "btn_init": "// INITIALIZE SYSTEM ►",
    "ql1": "CROP ANALYSIS", "ql2": "DISEASE SCAN", "ql3": "WEATHER INTEL",
    "ql4": "MARKET PRICES", "ql5": "MAGI QUERY", "ql6": "FEDERAL DIRECTIVES",
    "footer": "AMRITKRISHI 2.0 // NERV AGRI DIVISION // CLASSIFIED LEVEL 3 // 2026"
}

TA_NGE = {
    "nav_sys_online": "MAGI சிஸ்டம் v2.0 // ஆன்லைன்",
    "nav_sys_class": "// நெர்வ் வேளாண்மைப் பிரிவு // ரகசியம்",
    "hero_eyebrow": "// மேகி வேளாண்மை நுண்ணறிவு சிஸ்டம்",
    "hero_title": "அமிர்த்கிருஷி",
    "enter_sys": "உள்ளே நுழைய ►",
    "learn_more": "மேலும் அறிய ↓",
    "scroll": "↓ ஆராய கீழே செல்லவும் ↓",
    "hero_sub1": "இந்திய விவசாயிகளுக்கான AI-அடிப்படையிலான பயிர் நுண்ணறிவு",
    "hero_sub2": "இலை படங்களிலிருந்து நிகழ்நேர நோயறிதல்",
    "hero_sub3": "500+ மண்டி இடங்களில் இருந்து நேரடி சந்தை விலைகள்",
    "hero_sub4": "தமிழ் | இந்தி | ஆங்கிலத்தில் கிடைக்கிறது",
    "mission_typed": "> 140 மில்லியன் இந்திய விவசாயிகள். பெரும்பாலோருக்கு நவீன விவசாய நுண்ணறிவு கிடைப்பதில்லை. அதை அமிர்த்கிருஷி மாற்றுகிறது.",
    "mission_dir": "// முக்கிய நோக்கம்",
    "mission_title": "பிரச்சனை",
    "prob1_label": "ஆண்டுதோறும் நோயால் ஏற்படும் பயிர் மகசூல் இழப்பு",
    "prob2_label": "ஒவ்வொரு ஆண்டும் கோரப்படாத அரசு திட்டங்கள்",
    "prob3_label": "இடைத்தரகர்களால் சுரண்டப்படும் விவசாயிகள்",
    "feat_sys": "// அமைப்பின் திறன்கள்",
    "feat_title": "சிறப்பம்சங்கள்",
    "feat1_title": "பயிர் நுண்ணறிவு",
    "feat1_sub": "AI அடிப்படையிலான பரிந்துரை",
    "feat1_desc": "எந்த மாநிலத்தையும் மாவட்டத்தையும் தேர்ந்தெடுக்கவும். எங்களின் மாடல் நிகழ்நேர மண் மற்றும் வானிலையை பகுப்பாய்வு செய்து அதிக மகசூல் தரும் பயிரை பரிந்துரைக்கும்.",
    "feat1_s1": "22 பயிர் வகைகள்", "feat1_s2": "93% துல்லியம்", "feat1_s3": "அனைத்து 28 மாநிலங்கள்",
    "feat2_title": "உயிரியல் அச்சுறுத்தல் சோதனை",
    "feat2_sub": "CNN நோய் கண்டறிதல்",
    "feat2_desc": "இலையின் புகைப்படத்தைப் பதிவேற்றவும். எங்களின் MobileNetV2 மாடல் 38 நோய்களைக் கண்டறிந்து சிகிச்சையை வழங்குகிறது.",
    "feat2_s1": "38 நோய்கள்", "feat2_s2": "85%+ துல்லியம்", "feat2_s3": "நேரடி சோதனை",
    "feat3_title": "வளிமண்டல நுண்ணறிவு",
    "feat3_sub": "நேரடி வானிலை + விவசாய எச்சரிக்கைகள்",
    "feat3_desc": "இந்தியாவின் அனைத்து நகரங்களுக்கும் நேரடி வானிலை உங்களை மழையளவும், உறைபனியும் பற்றிக் காக்கும்.",
    "feat3_s1": "நேரடி தரவு", "feat3_s2": "7-நாள் முன்னறிவிப்பு", "feat3_s3": "விவசாய எச்சரிக்கைகள்",
    "feat4_title": "சந்தை நுண்ணறிவு",
    "feat4_sub": "நேரடி மண்டி விலைகள்",
    "feat4_desc": "இந்தியாவின் அனைத்து மாநிலங்களிலிருந்தும் Agmarknet மூலம் பயிர் விலைகள்.",
    "feat4_s1": "500+ மண்டிகள்", "feat4_s2": "நேரடி விலைகள்", "feat4_s3": "விலை முன்னறிவிப்பு",
    "feat5_title": "மேகி வினவல் இடைமுகம்",
    "feat5_sub": "பன்மொழி AI சாட்போட்",
    "feat5_desc": "Google Gemini மூலம் இயங்குகிறது. விவசாயம் பற்றி தமிழ், இந்தி, அல்லது ஆங்கிலத்தில் கேட்கலாம்.",
    "feat5_s1": "3 மொழிகள்", "feat5_s2": "Gemini AI", "feat5_s3": "24/7 கிடைக்கும்",
    "feat6_title": "அரசு வழிகாட்டுதல்கள்",
    "feat6_sub": "அரசு திட்டம் தேடல்",
    "feat6_desc": "PM-KISAN மற்றும் பிற 15+ அரசு திட்டங்கள். தகுதிகளை சரிபார்த்து நேராக விண்ணப்பிக்கலாம்.",
    "feat6_s1": "15+ திட்டங்கள்", "feat6_s2": "தகுதி சரிபார்ப்பு", "feat6_s3": "நேரடி விண்ணப்பம்",
    "stat_sys": "// அமைப்பின் அளவீடுகள்",
    "stat_title": "எண்களின் அடிப்படையில்",
    "stat1_l": "இந்திய விவசாயிகள்", "stat1_d": "இந்தியா முழுவதும் உள்ள பயனர்கள்",
    "stat2_l": "பயிர் துல்லியம்", "stat2_d": "சோதனை தரவுகளில்",
    "stat3_l": "நோய் கண்டறிதல்", "stat3_d": "MobileNetV2 துல்லியம்",
    "stat4_l": "நோய் வகைகள்", "stat4_d": "தாவர நோய்கள் கண்டறியப்பட்டன",
    "stat5_l": "பயிர் வகைகள்", "stat5_d": "பரிந்துரை ஆதரிக்கப்படுகிறது",
    "stat6_l": "மொழிகள்", "stat6_d": "தமிழ், இந்தி, ஆங்கிலம்",
    "stat7_l": "மண்டி இடங்கள்", "stat7_d": "நேரடி விலை தகவல்கள்",
    "stat8_l": "அரசு திட்டங்கள்", "stat8_d": "கண்டுபிடிக்கக்கூடிய திட்டங்கள்",
    "tech_sys": "// தொழில்நுட்ப கட்டமைப்பு",
    "tech_title": "தொழில்நுட்பங்கள்",
    "demo_sys": "// சிஸ்டம் செயல்விளக்கம்",
    "demo_title": "இது எப்படி வேலை செய்கிறது",
    "demo_step": "// படி {step} இல் {total}",
    "d1_t": "மாநிலத்தை தேர்வுசெய்க", "d1_d": "இந்திய வரைபடத்தில் தமிழ்நாட்டை கிளிக் செய்யவும்",
    "d2_t": "மாவட்டத்தை தேர்வுசெய்க", "d2_d": "மாவட்டக் கட்டத்தில் சென்னையை தேர்வு செய்யவும்",
    "d3_t": "AI பகுப்பாய்வு", "d3_d": "மேகி நேரடி வானிலை மற்றும் மண் தரவைக் கொண்டு ML மாதிரியை இயக்குகிறது",
    "d4_t": "முடிவைப் பெறுக", "d4_d": "92% நம்பிக்கையுடன் நெல் பரிந்துரைக்கப்படுகிறது",
    "d5_t": "நோயை கண்டறிக", "d5_d": "இலையின் படத்தைப் பதிவேற்றவும் → CNN 2 வினாடிகளில் நோய்களைக் கண்டறியும்",
    "d6_t": "AI-யை தமிழில் கேளுங்கள்", "d6_d": "தமிழில் கேள்வியைத் தட்டச்சு செய்க → Gemini தமிழில் உடனடியாக பதிலளிக்கும்",
    "enter_sys_rdy": "// சிஸ்டம் தயாராக உள்ளது",
    "enter_title": "அமிர்த்கிருஷிக்குள் நுழையவும்",
    "enter_typed": "> மேகி சிஸ்டம் முழுமையாக இயங்குகிறது\\n> அனைத்து தொகுதிகளும் ஆன்லைனில் உள்ளன\\n> உங்கள் உள்ளீட்டிற்காக காத்திருக்கிறது...",
    "btn_init": "// அமைப்பைத் தொடங்கவும் ►",
    "ql1": "பயிர் பகுப்பாய்வு", "ql2": "நோய் ஸ்கேன்", "ql3": "வானிலை தகவல்",
    "ql4": "சந்தை விலைகள்", "ql5": "மேகி வினவல்", "ql6": "அரசு திட்டங்கள்",
    "footer": "அமிர்த்கிருஷி 2.0 // நெர்வ் வேளாண்மைப் பிரிவு // ரகசியம் நிலை 3 // 2026"
}

HI_NGE = {
    "nav_sys_online": "MAGI सिस्टम v2.0 // ऑनलाइन",
    "nav_sys_class": "// NERV कृषि विभाग // गोपनीय",
    "hero_eyebrow": "// MAGI कृषि खुफिया सिस्टम",
    "hero_title": "अमृतकृषि",
    "enter_sys": "सिस्टम में प्रवेश करें ►",
    "learn_more": "और जानें ↓",
    "scroll": "↓ एक्सप्लोर करने के लिए स्क्रॉल करें ↓",
    "hero_sub1": "भारतीय किसानों के लिए एआई-संचालित फसल खुफिया",
    "hero_sub2": "पत्तियों की छवियों से रीयल-टाइम रोग का पता लगाना",
    "hero_sub3": "500+ मंडियों से लाइव बाजार की कीमतें",
    "hero_sub4": "तमिल | हिंदी | अंग्रेजी में उपलब्ध",
    "mission_typed": "> 140 मिलियन भारतीय किसान। बिना किसी आधुनिक कृषि बुद्धिमत्ता के। अमृतकृषि इसे बदलता है।",
    "mission_dir": "// मिशन निर्देश",
    "mission_title": "समस्या",
    "prob1_label": "प्रती वर्ष बीमारी से फसल का नुकसान",
    "prob2_label": "हर साल अप्रयुक्त सरकारी योजनाएं",
    "prob3_label": "बिचौलियों द्वारा किसानों का शोषण",
    "feat_sys": "// सिस्टम क्षमताएँ",
    "feat_title": "विशेषताएँ",
    "feat1_title": "फसल खुफिया",
    "feat1_sub": "एआई-संचालित सिफारिश",
    "feat1_desc": "किसी भी राज्य और जिले का चयन करें। हमारा मॉडल रीयल-टाइम मिट्टी + मौसम डेटा का विश्लेषण करता है।",
    "feat1_s1": "22 फ़सल के प्रकार", "feat1_s2": "93% सटीकता", "feat1_s3": "सभी 28 राज्य",
    "feat2_title": "जैविक खतरा स्कैन",
    "feat2_sub": "सीएनएन रोग निवारण",
    "feat2_desc": "फोटो अपलोड करें। हमारा MobileNetV2 सिस्टम 38 बीमारियों के लिए स्कैन करता है।",
    "feat2_s1": "38 बीमारी वर्ग", "feat2_s2": "85%+ सटीकता", "feat2_s3": "रीयल-टाइम स्कैन",
    "feat3_title": "वायुमंडलीय खुफिया",
    "feat3_sub": "लाइव मौसम + खेती अलर्ट",
    "feat3_desc": "भारत के हर शहर के लिए लाइव मौसम। सूखा, पाला, और बारिश के लिए अलर्ट।",
    "feat3_s1": "लाइव डेटा", "feat3_s2": "7-दिन का पूर्वानुमान", "feat3_s3": "कृषि अलर्ट",
    "feat4_title": "बाजार इंटेलिजेंस",
    "feat4_sub": "लाइव मंडी कीमतें",
    "feat4_desc": "सभी राज्यों में एगमार्कनेट से लाइव फसल कीमतें। कीमत का पूर्वानुमान और सिफारिशें।",
    "feat4_s1": "500+ मंडियां", "feat4_s2": "विशाल कीमतें", "feat4_s3": "मूल्य भविष्यवाणी",
    "feat5_title": "MAGI क्वेरी इंटरफ़ेस",
    "feat5_sub": "बहुभाषी एआई चैटबॉट",
    "feat5_desc": "Google Gemini द्वारा संचालित। तमिल, हिंदी या अंग्रेजी में कृषि के बारे में पूछें।",
    "feat5_s1": "3 भाषाएँ", "feat5_s2": "जेमिनी एआई", "feat5_s3": "24/7 उपलब्ध",
    "feat6_title": "सरकारी निर्देश",
    "feat6_sub": "सरकारी योजना खोजक",
    "feat6_desc": "पीएम-किसान सहित 15+ सरकारी योजनाएं। पात्रता और लाइव आवेदन लिंक।",
    "feat6_s1": "15+ योजनाएं", "feat6_s2": "पात्रता जाँच", "feat6_s3": "सीधा आवेदन",
    "stat_sys": "// सिस्टम मेट्रिक्स",
    "stat_title": "आंकड़ों में",
    "stat1_l": "भारतीय किसान", "stat1_d": "पूरे भारत में संभावित उपयोगकर्ता",
    "stat2_l": "फसल सटीकता", "stat2_d": "परीक्षण डेटासेट पर",
    "stat3_l": "रोग निवारण", "stat3_d": "MobileNetV2 सटीकता",
    "stat4_l": "बीमारी के प्रकार", "stat4_d": "पोधों में बीमारियों का पता चला",
    "stat5_l": "फसल के प्रकार", "stat5_d": "अनुशंसा समर्थित",
    "stat6_l": "भाषाएँ", "stat6_d": "तमिल, हिंदी, अंग्रेजी",
    "stat7_l": "मंडी स्थान", "stat7_d": "लाइव मूल्य कवरेज",
    "stat8_l": "सरकारी योजनाएं", "stat8_d": "खोजने योग्य योजनाएं",
    "tech_sys": "// सिस्टम वास्तुकला",
    "tech_title": "टेक स्टैक",
    "demo_sys": "// सिस्टम प्रदर्शन",
    "demo_title": "यह कैसे काम करता है",
    "demo_step": "// चरण {step} / {total}",
    "d1_t": "राज्य चुनें", "d1_d": "भारत के इंटरेक्टिव मानचित्र पर तमिलनाडु पर क्लिक करें",
    "d2_t": "जिला चुनें", "d2_d": "ज़िला ग्रिड से चेन्नई चुनें",
    "d3_t": "एआई विश्लेषण", "d3_d": "MAGI लाइव मौसम + मिट्टी का डेटा लाता है और ML मॉडल चलाता है",
    "d4_t": "परिणाम प्राप्त करें", "d4_d": "92% विश्वास के साथ चावल की सिफारिश की गई",
    "d5_t": "रोग का पता लगाएं", "d5_d": "पत्ती का फोटो अपलोड करें → CNN 2 सेकंड में 38 बीमारियों को स्कैन करता है",
    "d6_t": "हिंदी में एआई से पूछें", "d6_d": "हिंदी में सवाल टाइप करें → Gemini हिंदी में जवाब देता है",
    "enter_sys_rdy": "// सिस्टम तैयार है",
    "enter_title": "अमृतकृषि में प्रवेश करें",
    "enter_typed": "> MAGI सिस्टम पूरी तरह चालू है\\n> सभी मॉड्यूल ऑनलाइन हैं\\n> ऑपरेटर के इनपुट की प्रतीक्षा कर रहा है...",
    "btn_init": "// सिस्टम प्रारंभ करें ►",
    "ql1": "फसल विश्लेषण", "ql2": "रोग स्कैन", "ql3": "मौसम जानकारी",
    "ql4": "बाजार मूल्य", "ql5": "MAGI क्वेरी", "ql6": "सरकारी निर्देश",
    "footer": "अमृतकृषि 2.0 // NERV कृषि विभाग // गोपनीय स्तर 3 // 2026"
}

def update_json(lang, new_data):
    filepath = f"frontend/src/i18n/{lang}.json"
    if os.path.exists(filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
    else:
        data = {}
        
    data["dash_nge"] = new_data
    
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

update_json("en", EN_NGE)
update_json("ta", TA_NGE)
update_json("hi", HI_NGE)
print("Dictionaries updated successfully!")
